[alias]
build-all = "build --workspace"

build-tui = "build -p oxidrive-tui"
run-tui = "run -p oxidrive-tui"

build-android = "apk2 build -p oxidrive-gui-android --target aarch64-linux-android --lib"
run-android = "apk2 run -p oxidrive-gui-android --target aarch64-linux-android --lib"

