import {
	MaterialWindow
} from "@material";

import { AppStrings } from "@root/strings.slint";

import {
	MainWindowAdapter
} from "@root/window/main_window_adapter.slint";

import {
	MainView
} from "@root/views.slint";

import "@fonts/Roboto-VariableFont.ttf";

export component MainWindow inherits MaterialWindow {
	title: AppStrings.data.app_name;
    default-font-family: "Roboto";

	preferred-width: 600px;
    preferred-height: 400px;

    MainView {
	    x: root.safe-area-insets.left;
	    y: root.safe-area-insets.top;
	    width: root.width - root.safe-area-insets.right - root.safe-area-insets.left;
	    height: root.height - root.safe-area-insets.bottom - root.safe-area-insets.top;
    }

	changed width => {
        MainWindowAdapter.width = root.width;
    }

    changed height => {
        MainWindowAdapter.height = root.height;
    }
}

