name: Unified CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit

  android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

